# Generated by Django 4.2.30 on 2026-05-10 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("keywords", models.JSONField(default=list)),
                ("year", models.CharField(blank=True, default="", max_length=20)),
                ("summary", models.TextField()),
                (
                    "source",
                    models.CharField(blank=True, default="local", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "paper_record",
            },
        ),
        migrations.CreateModel(
            name="RagHitRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_hits",
                        to="papers.paperrecord",
                    ),
                ),
            ],
            options={
                "db_table": "rag_hit_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
