# Generated by Django 4.2.30 on 2026-05-10 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="新会话", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_task",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "last_skill",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            options={
                "db_table": "chat_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolCallRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=100)),
                ("query", models.TextField(blank=True, default="")),
                ("status", models.CharField(default="success", max_length=50)),
                ("result_summary", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "tool_call_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentTaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                ("task_type", models.CharField(blank=True, default="", max_length=100)),
                (
                    "triggered_skills",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("used_rag", models.BooleanField(default=False)),
                ("used_web_search", models.BooleanField(default=False)),
                ("status", models.CharField(default="success", max_length=50)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "agent_task_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
